name: Greeting on variable day


#Nivel de env
#The entire workflow, by using env at the top level of the workflow file.
#The contents of a job within a workflow, by using jobs.<job_id>.env.
#A specific step within a job, by using jobs.<job_id>.steps[*].env.

on:
  workflow_dispatch
#Demostración de uso de variable en workflow
env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
#Notese este env también
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
#Notese este env también
        env:
          First_Name: Mona